---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-template"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: "template.${NAME}-cron-secret"
  type: Opaque
  stringData:
    webhookUrl: "${SSO_WEBHOOK_URL}"
parameters:
- name: "NAME"
  displayName: "Job Name"
  description: "Name of the Scheduled Job to Create."
  value: "audit-logs-backup"
  required: true
- name: "SUFFIX"
  description: "A suffix appended to most objects"
  displayName: "Application Suffix"
  value: ""
- name: "SSO_WEBHOOK_URL"
  displayName: "notification webhook"
  description: "Rocketchat notification webhook."
  value: ''
  required: true
