apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}-replica
  labels:
    app.kubernetes.io/name: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "patroni.fullname" . }}
    role: replica
