apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: 6d70e7-team
  namespace: 6d70e7-tools
spec:
  team: 
    description: The Sysdig Team for the SSO Prod Namespaces
    users:
    - name: c.gustafson@cgi.com
      role: ROLE_TEAM_MANAGER 
    - name: patricksimonian@gmail.com
      role: ROLE_TEAM_EDIT
    - name: shelly.han@gov.bc.ca
      role: ROLE_TEAM_EDIT
    - name: niranv22@gmail.com
      role: ROLE_TEAM_MANAGER
    - name: arcshiftsolutions@gmail.com
      role: ROLE_TEAM_MANAGER 
    - name: bryce.reid@cgi.com
      role: ROLE_TEAM_EDIT 
    - name: zorin.samji@gov.bc.ca
      role: ROLE_TEAM_MANAGER
    - name: jon@button.is
      role: ROLE_TEAM_MANAGER
    - name: junmin@button.is
      role: ROLE_TEAM_MANAGER
