apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sso72-x509-postgresql-persistent
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}-postgresql${SUFFIX}
    annotations:
      as-copy-of: "template.${NAME}-postgresql"
  type: Opaque
  stringData:
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    database: "${DB_DATABASE}"
parameters:
- description: The name for the application.
  displayName: Application Name
  name: NAME
  required: true
- description: A suffix appended to most objects
  displayName: Application Suffix
  name: SUFFIX
  value: ""
- description: Database name
  displayName: Database Name
  name: DB_DATABASE
  required: true
  value: root
- description: Database user name
  displayName: Database Username
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: DB_USERNAME
  required: true
- description: Database user password
  displayName: Database Password
  from: '[a-zA-Z0-9]{32}'
  generate: expression
  name: DB_PASSWORD
  required: true