apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      shared: "true"
    name: sso72-openshift
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-sso-7/sso72-openshift:${RH_SSO_IMAGE_TAG}
      importPolicy: {}
      name: ${RH_SSO_IMAGE_TAG}
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: null
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels: {}
    name: ${NAME}${SUFFIX}
  spec:
    completionDeadlineSeconds: 1440
    failedBuildsHistoryLimit: 3
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    runPolicy: SerialLatestOnly
    source:
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URL}
      type: Git
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: sso72-openshift:${RH_SSO_IMAGE_TAG}
      type: Docker
    successfulBuildsHistoryLimit: 3
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: Name used for all created objects
  displayName: Name
  name: NAME
  required: true
  value: sso72-bcgov
- description: A suffix appended to all objects
  name: SUFFIX
  value: -build
- name: RH_SSO_IMAGE_TAG
  required: true
  value: 1.3-7
- name: VERSION
  decription: The output tag name created by the build config
  required: true
  value: latest
- name: SOURCE_GIT_URL
  required: true
  value: https://github.com/bcgov/ocp-sso.git
- name: SOURCE_GIT_REF
  required: false
  value: add-docker-file
- name: SOURCE_CONTEXT_DIR
  value: "docker"