apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sso73-x509-postgresql-persistent
objects:
- apiVersion: v1
  kind: Secret
  labels:
    name: ${NAME}${SUFFIX}
  metadata:
    name: ${NAME}-jgroups${SUFFIX}
    annotations:
      as-copy-of: "template.${NAME}-jgroups"
  type: Opaque
  stringData:
    password: "${JGROUPS_CLUSTER_PASSWORD}"
- apiVersion: v1
  kind: Secret
  labels:
    name: ${NAME}${SUFFIX}
  metadata:
    name: ${NAME}-admin${SUFFIX}
    annotations:
      as-copy-of: "template.${NAME}-admin"
  type: Opaque
  stringData:
    username: "${SSO_ADMIN_USERNAME}"
    password: "${SSO_ADMIN_PASSWORD}"
parameters:
- description: The name for the application.
  displayName: Application Name
  name: NAME
  required: true
  value: sso
- description: A suffix appended to most objects
  displayName: Application Suffix
  name: SUFFIX
  value: ""
- description: The password for the JGroups cluster.
  displayName: JGroups Cluster Password
  from: '[a-zA-Z0-9]{32}'
  generate: expression
  name: JGROUPS_CLUSTER_PASSWORD
  required: true
- description: RH-SSO Server administrator username
  displayName: RH-SSO Administrator Username
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: SSO_ADMIN_USERNAME
  required: true
- description: RH-SSO Server administrator password
  displayName: RH-SSO Administrator Password
  from: '[a-zA-Z0-9]{32}'
  generate: expression
  name: SSO_ADMIN_PASSWORD
  required: true