---
- name: Login to Cluster A
  shell: oc config use-context {{ migrator_vars.cluster_a.context }}

- name: Create Cluster B service account token secret in Cluster A 
  shell: oc apply -f {{ CLUSTER_B_SA_SECRET }} -n {{ migrator_vars.cluster_a.namespace }}

- name: Delete Temp Secret file 
  ansible.builtin.file:
    path: "{{ CLUSTER_B_SA_SECRET }}"
    state: absent
  when: CLUSTER_B_SA_SECRET is defined

- name: Checking if migrator image exists
  shell: oc get -n {{ migrator_vars.cluster_a.migrator.namespace }} imagestreamtag {{ migrator_vars.cluster_a.migrator.name }}:{{ migrator_vars.cluster_a.migrator.tag }} 
  register: imagestreamtag
  ignore_errors: yes 

- name: Building migrator image in {{ migrator_vars.cluster_a.migrator.namespace }}
  shell: |
    curl https://raw.githubusercontent.com/BCDevOps/StorageMigration/master/openshift/templates/pvc-migrator-build.yaml |
    oc process -f - -n {{ migrator_vars.cluster_a.migrator.namespace }} |
    oc apply -f - -n {{ migrator_vars.cluster_a.migrator.namespace }}
  when: imagestreamtag.stdout in 'NotFound'

- name: Deploying Migrator Image
  shell: |
    curl https://raw.githubusercontent.com/BCDevOps/StorageMigration/master/cross-cluster/source-migrator-tmpl.yaml |
    oc process -f - -n {{ migrator_vars.cluster_a.namespace }} \
    -p SOURCE_PVC={{ migrator_vars.cluster_a.pvc }} \
    -p REMOTE_CLUSTER={{ migrator_vars.cluster_b.server_url }} \
    -p REMOTE_PROJECT={{ migrator_vars.cluster_b.namespace }} \
    -p REMOTE_SECRET={{ CLUSTER_B_SA_SECRET_NAME }} \
    -p SRC_IMAGE_NAME={{ migrator_vars.cluster_a.migrator.name }} \ 
    -p TAG_NAME={{ migrator_vars.cluster_a.migrator.tag }} \  
    -p SRC_IMAGE_NAMESPACE={{ migrator_vars.cluster_a.migrator.namespace }} \  
    -p SRC_IMAGE_REGISTRY={{ migrator_vars.cluster_a.image_registry }} \
    -p NAME={{ migrator_vars.cluster_a.migrator.name }}-{{ migrator_vars.cluster_a.name }} |
    oc apply -f - -n {{ migrator_vars.cluster_a.namespace }}


- name: Wait for migrator pod to be ready
  include_tasks: ./wait_for_scale_up.yml
  vars:
    TARGET_NAMESPACE: "{{ migrator_vars.cluster_a.namespace }}"
    KIND: Deployment
    OBJECT_NAME: "{{ migrator_vars.cluster_a.migrator.name }}-{{ migrator_vars.cluster_a.name }}"
  