---
- name: Login to Cluster A
  shell: oc config use-context {{ migrator_vars.cluster_a.context }}

- name: Get Cluster A Migrator Pod Name
  shell: | 
    oc -n {{ migrator_vars.cluster_a.namespace }} get pods -o name | 
    grep '{{ migrator_vars.cluster_a.migrator.name }}-{{ migrator_vars.cluster_a.name }}' |
    awk '{print $1}'
  register: oc_output

- name: setting cluster a pod name
  set_fact:
    CLUSTER_A_MIGRATOR_POD: "{{ oc_output.stdout }}"

- name: Login to Cluster b
  shell: oc config use-context {{ migrator_vars.cluster_b.context }}

- name: Get Cluster b Migrator Pod Name
  shell: | 
    oc -n {{ migrator_vars.cluster_b.namespace }} get pods -o name | 
    grep '{{ migrator_vars.cluster_b.migrator.name }}-{{ migrator_vars.cluster_b.name }}' |
    awk '{print $1}'
  register: oc_b_output

- name: setting cluster b pod name
  set_fact:
    CLUSTER_B_MIGRATOR_POD: "{{ oc_b_output.stdout }}"

