- debug: 
    msg: "--------- Changing context to {{ migrator_vars.cluster_a.server_url }} ---------"

- name: "Checking logged into this cluster: {{ migrator_vars.cluster_a.server_url }}"
  shell: |
    oc config use-context {{ migrator_vars.cluster_a.context }}
    oc whoami
  register: source_login
  failed_when: source_login.stdout in 'Forbidden'

- name: "Checking logged into this cluster: {{ migrator_vars.cluster_b.server_url }}"
  shell: |
    oc config use-context {{ migrator_vars.cluster_b.context }}
    oc whoami
  register: source_login
  failed_when: source_login.stdout in 'Forbidden'

  